module RiskProfilesHelper
  def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end

  def us_counties
    [
      ["Alameda", "Alameda"],
      ["Alpine", "Alpine"],
      ["Amador", "Amador"],
      ["Butte", "Butte"],
      ["Calaveras", "Calaveras"],
      ["Colusa", "Colusa"],
      ["Contra Costa", "Contra Costa"],
      ["Del Norte", "Del Norte"],
      ["El Dorado", "El Dorado"],
      ["Fresno", "Fresno"],
      ["Glenn", "Glenn"],
      ["Humboldt", "Humboldt"],
      ["Imperial", "Imperial"],
      ["Inyo", "Inyo"],
      ["Kern", "Kern"],
      ["Kings", "Kings"],
      ["Lake", "Lake"],
      ["Lassen", "Lassen"],
      ["Los Angeles", "Los Angeles"],
      ["Madera", "Madera"],
      ["Marin", "Marin"],
      ["Mariposa", "Mariposa"],
      ["Mendocino", "Mendocino"],
      ["Merced", "Merced"],
      ["Modoc", "Modoc"],
      ["Mono", "Mono"],
      ["Monterey", "Monterey"],
      ["Napa", "Napa"],
      ["Nevada", "Nevada"],
      ["Orange", "Orange"],
      ["Placer", "Placer"],
      ["Plumas", "Plumas"],
      ["Riverside", "Riverside"],
      ["Sacramento", "Sacramento"],
      ["San Benito", "San Benito"],
      ["San Bernardino", "San Bernardino"],
      ["San Diego", "San Diego"],
      ["San Francisco, City", "San Francisco, City"],
      ["San Joaquin", "San Joaquin"],
      ["San Luis Obispo", "San Luis Obispo"],
      ["San Mateo", "San Mateo"],
      ["Santa Barbara", "Santa Barbara"],
      ["Santa Clara", "Santa Clara"],
      ["Santa Cruz", "Santa Cruz"],
      ["Shasta", "Shasta"],
      ["Sierra", "Sierra"],
      ["Siskiyou", "Siskiyou"],
      ["Solano", "Solano"],
      ["Sonoma", "Sonoma"],
      ["Stanislaus", "Stanislaus"],
      ["Sutter", "Sutter"],
      ["Tehama", "Tehama"],
      ["Trinity", "Trinity"],
      ["Tulare", "Tulare"],
      ["Tuolumne", "Tuolumne"],
      ["Ventura", "Ventura"],
      ["Yolo", "Yolo"],
      ["Yuba", "Yuba"]
    ]
  end

end
