# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Seed Initial Rates + Factors
DedFactor.create!(factor: 1.00, deductible: 00000)
DedFactor.create!(factor: 0.95, deductible: 05000)
DedFactor.create!(factor: 0.90, deductible: 10000)
DedFactor.create!(factor: 0.80, deductible: 25000)

EntityFactor.create!(factor: 1.08, entity: true)
EntityFactor.create!(factor: 1.00, entity: false)

LimitFactor.create!(factor: 1.000, limit: "1000000_3000000", state:  "AZ")
LimitFactor.create!(factor: 0.662, limit: "300000", state:  "AZ")
LimitFactor.create!(factor: 1.000, limit: "500000_1000000", state:  "ID")
LimitFactor.create!(factor: 1.760, limit: "1000000_3000000", state:  "ID")
LimitFactor.create!(factor: 1.000, limit: "1000000_3000000", state:  "NC")
LimitFactor.create!(factor: 1.000, limit: "1000000_3000000", state:  "CO")
LimitFactor.create!(factor: 0.591, limit: "100000_300000", state:  "CO")
LimitFactor.create!(factor: 0.878, limit: "500000_1500000", state:  "CO")
LimitFactor.create!(factor: 1.000, limit: "1000000_3000000", state:  "MD")
LimitFactor.create!(factor: 1.000, limit: "1000000_3000000", state:  "OH")
LimitFactor.create!(factor: 1.000, limit: "1000000_3000000", state:  "GA")
LimitFactor.create!(factor: 0.958, limit: "1000000_1000000", state:  "GA")
LimitFactor.create!(factor: 0.814, limit: "500000_1000000", state:  "GA")
LimitFactor.create!(factor: 1.000, limit: "1000000_3000000", state:  "NY")
LimitFactor.create!(factor: 1.060, limit: "1300000_3900000", state:  "NY")
LimitFactor.create!(factor: 1.000, limit: "1000000_3000000", state:  "WA")

StepFactor.create!(policy_year: "1",  factor: 0.300, state:  "AZ")
StepFactor.create!(policy_year: "2",  factor: 0.500, state:  "AZ")
StepFactor.create!(policy_year: "3",  factor: 0.800, state:  "AZ")
StepFactor.create!(policy_year: "4+", factor: 1.000, state:  "AZ")
StepFactor.create!(policy_year: "1",  factor: 0.300, state:  "ID")
StepFactor.create!(policy_year: "2",  factor: 0.590, state:  "ID")
StepFactor.create!(policy_year: "3",  factor: 0.750, state:  "ID")
StepFactor.create!(policy_year: "4",  factor: 0.810, state:  "ID")
StepFactor.create!(policy_year: "5",  factor: 0.880, state:  "ID")
StepFactor.create!(policy_year: "6+", factor: 1.000, state:  "ID")
StepFactor.create!(policy_year: "1",  factor: 0.300, state:  "NC")
StepFactor.create!(policy_year: "2",  factor: 0.550, state:  "NC")
StepFactor.create!(policy_year: "3",  factor: 0.775, state:  "NC")
StepFactor.create!(policy_year: "4",  factor: 0.930, state:  "NC")
StepFactor.create!(policy_year: "5+", factor: 1.000, state:  "NC")
StepFactor.create!(policy_year: "1",  factor: 0.631, state:  "CO")
StepFactor.create!(policy_year: "2",  factor: 0.778, state:  "CO")
StepFactor.create!(policy_year: "3",  factor: 0.889, state:  "CO")
StepFactor.create!(policy_year: "4+", factor: 1.000, state:  "CO")
StepFactor.create!(policy_year: "1",  factor: 0.230, state:  "MD")
StepFactor.create!(policy_year: "2",  factor: 0.480, state:  "MD")
StepFactor.create!(policy_year: "3",  factor: 0.710, state:  "MD")
StepFactor.create!(policy_year: "4",  factor: 0.890, state:  "MD")
StepFactor.create!(policy_year: "5+", factor: 1.000, state:  "MD")
StepFactor.create!(policy_year: "1",  factor: 0.355, state:  "OH")
StepFactor.create!(policy_year: "2",  factor: 0.631, state:  "OH")
StepFactor.create!(policy_year: "3",  factor: 0.862, state:  "OH")
StepFactor.create!(policy_year: "4",  factor: 0.926, state:  "OH")
StepFactor.create!(policy_year: "5+", factor: 1.000, state:  "OH")
StepFactor.create!(policy_year: "1",  factor: 0.319, state:  "GA")
StepFactor.create!(policy_year: "2",  factor: 0.592, state:  "GA")
StepFactor.create!(policy_year: "3",  factor: 0.909, state:  "GA")
StepFactor.create!(policy_year: "4",  factor: 0.955, state:  "GA")
StepFactor.create!(policy_year: "5+", factor: 1.000, state:  "GA")
StepFactor.create!(policy_year: "1",  factor: 0.295, state:  "NY")
StepFactor.create!(policy_year: "2",  factor: 0.610, state:  "NY")
StepFactor.create!(policy_year: "3",  factor: 0.809, state:  "NY")
StepFactor.create!(policy_year: "4",  factor: 0.895, state:  "NY")
StepFactor.create!(policy_year: "5",  factor: 0.943, state:  "NY")
StepFactor.create!(policy_year: "6",  factor: 0.971, state:  "NY")
StepFactor.create!(policy_year: "7",  factor: 0.991, state:  "NY")
StepFactor.create!(policy_year: "8+", factor: 1.000, state:  "NY")
StepFactor.create!(policy_year: "1",  factor: 0.317, state:  "WA")
StepFactor.create!(policy_year: "2",  factor: 0.536, state:  "WA")
StepFactor.create!(policy_year: "3",  factor: 0.705, state:  "WA")
StepFactor.create!(policy_year: "4",  factor: 0.875, state:  "WA")
StepFactor.create!(policy_year: "5+", factor: 1.000, state:  "WA")
StepFactor.create!(policy_year: "1",  factor: 0.350, state:  "CA")
StepFactor.create!(policy_year: "2",  factor: 0.600, state:  "CA")
StepFactor.create!(policy_year: "3",  factor: 0.800, state:  "CA")
StepFactor.create!(policy_year: "4",  factor: 0.920, state:  "CA")
StepFactor.create!(policy_year: "5+", factor: 1.000, state:  "CA")

TerritoryFactor.create!(factor: 0.800, territory: "Catoosa", number: 1, exposure: 0.043, state: "GA")
TerritoryFactor.create!(factor: 0.800, territory: "Chattooga", number: 1, exposure: 0.043, state: "GA")
TerritoryFactor.create!(factor: 0.800, territory: "Dade", number: 1, exposure: 0.043, state: "GA")
TerritoryFactor.create!(factor: 0.800, territory: "Fannin", number: 1, exposure: 0.043, state: "GA")
TerritoryFactor.create!(factor: 0.800, territory: "Floyd", number: 1, exposure: 0.043, state: "GA")
TerritoryFactor.create!(factor: 0.800, territory: "Gilmer", number: 1, exposure: 0.043, state: "GA")
TerritoryFactor.create!(factor: 0.800, territory: "Murray", number: 1, exposure: 0.043, state: "GA")
TerritoryFactor.create!(factor: 0.800, territory: "Rabun", number: 1, exposure: 0.043, state: "GA")
TerritoryFactor.create!(factor: 0.800, territory: "Towns", number: 1, exposure: 0.043, state: "GA")
TerritoryFactor.create!(factor: 0.800, territory: "Union", number: 1, exposure: 0.043, state: "GA")
TerritoryFactor.create!(factor: 0.800, territory: "Walker", number: 1, exposure: 0.043, state: "GA")
TerritoryFactor.create!(factor: 0.800, territory: "Whitfield", number: 1, exposure: 0.043, state: "GA")
TerritoryFactor.create!(factor: 1.000, territory: "Remainder", number: 2, exposure: 0.957, state: "GA")
TerritoryFactor.create!(factor: 1.000, territory: "Remainder", number: 1, exposure: 0.405, state: "MD")
TerritoryFactor.create!(factor: 1.136, territory: "Montgomery", number: 2, exposure: 0.455, state: "MD")
TerritoryFactor.create!(factor: 1.136, territory: "Prince George\'s", number: 2, exposure: 0.455, state: "MD")
TerritoryFactor.create!(factor: 1.136, territory: "Howard", number: 2, exposure: 0.455, state: "MD")
TerritoryFactor.create!(factor: 1.136, territory: "Anne Arundel", number: 2, exposure: 0.455, state: "MD")
TerritoryFactor.create!(factor: 1.250, territory: "Baltimore City", number: 3, exposure: 0.013, state: "MD")
TerritoryFactor.create!(factor: 1.250, territory: "Baltimore County", number: 3, exposure: 0.013, state: "MD")
TerritoryFactor.create!(factor: 2.745, territory: "Remainder", number: 0, exposure: 0.259, state: "NY")
TerritoryFactor.create!(factor: 2.745, territory: "New York", number: 1, exposure: 0.212, state: "NY")
TerritoryFactor.create!(factor: 2.745, territory: "Orange", number: 1, exposure: 0.212, state: "NY")
TerritoryFactor.create!(factor: 2.745, territory: "Rockland", number: 1, exposure: 0.212, state: "NY")
TerritoryFactor.create!(factor: 2.745, territory: "Sullivan", number: 1, exposure: 0.212, state: "NY")
TerritoryFactor.create!(factor: 2.745, territory: "Westchester", number: 1, exposure: 0.212, state: "NY")
TerritoryFactor.create!(factor: 3.256, territory: "Bronx", number: 2, exposure: 0.172, state: "NY")
TerritoryFactor.create!(factor: 3.256, territory: "Kings", number: 2, exposure: 0.172, state: "NY")
TerritoryFactor.create!(factor: 3.256, territory: "Queens", number: 2, exposure: 0.172, state: "NY")
TerritoryFactor.create!(factor: 3.256, territory: "Richmond", number: 2, exposure: 0.172, state: "NY")
TerritoryFactor.create!(factor: 3.548, territory: "Nassau", number: 3, exposure: 0.171, state: "NY")
TerritoryFactor.create!(factor: 3.548, territory: "Suffolk", number: 3, exposure: 0.171, state: "NY")
TerritoryFactor.create!(factor: 1.685, territory: "Columbia", number: 4, exposure: 0.045, state: "NY")
TerritoryFactor.create!(factor: 1.685, territory: "Duchess", number: 4, exposure: 0.045, state: "NY")
TerritoryFactor.create!(factor: 1.685, territory: "Greene", number: 4, exposure: 0.045, state: "NY")
TerritoryFactor.create!(factor: 1.685, territory: "Putnam", number: 4, exposure: 0.045, state: "NY")
TerritoryFactor.create!(factor: 1.685, territory: "Ulster", number: 4, exposure: 0.045, state: "NY")
TerritoryFactor.create!(factor: 1.059, territory: "Erie", number: 5, exposure: 0.087, state: "NY")
TerritoryFactor.create!(factor: 1.059, territory: "Niagra", number: 5, exposure: 0.087, state: "NY")
TerritoryFactor.create!(factor: 0.746, territory: "Livingston", number: 6, exposure: 0.054, state: "NY")
TerritoryFactor.create!(factor: 0.746, territory: "Monroe", number: 6, exposure: 0.054, state: "NY")
TerritoryFactor.create!(factor: 0.746, territory: "Ontario", number: 6, exposure: 0.054, state: "NY")
TerritoryFactor.create!(factor: 0.746, territory: "Seneca", number: 6, exposure: 0.054, state: "NY")
TerritoryFactor.create!(factor: 0.746, territory: "Wayne", number: 6, exposure: 0.054, state: "NY")
TerritoryFactor.create!(factor: 0.746, territory: "Yates", number: 6, exposure: 0.054, state: "NY")
TerritoryFactor.create!(factor: 1.000, territory: "Remainder", number: 1, exposure: 0.355, state: "OH")
TerritoryFactor.create!(factor: 0.770, territory: "Adams", number: 2, exposure: 0.296, state: "OH")
TerritoryFactor.create!(factor: 0.770, territory: "Brown", number: 2, exposure: 0.296, state: "OH")
TerritoryFactor.create!(factor: 0.770, territory: "Butler", number: 2, exposure: 0.296, state: "OH")
TerritoryFactor.create!(factor: 0.770, territory: "Champaign", number: 2, exposure: 0.296, state: "OH")
TerritoryFactor.create!(factor: 0.770, territory: "Clark", number: 2, exposure: 0.296, state: "OH")
TerritoryFactor.create!(factor: 0.770, territory: "Clemont", number: 2, exposure: 0.296, state: "OH")
TerritoryFactor.create!(factor: 0.770, territory: "Clinton", number: 2, exposure: 0.296, state: "OH")
TerritoryFactor.create!(factor: 0.770, territory: "Darke", number: 2, exposure: 0.296, state: "OH")
TerritoryFactor.create!(factor: 0.770, territory: "Greene", number: 2, exposure: 0.296, state: "OH")
TerritoryFactor.create!(factor: 0.770, territory: "Hamilton", number: 2, exposure: 0.296, state: "OH")
TerritoryFactor.create!(factor: 0.770, territory: "Highland", number: 2, exposure: 0.296, state: "OH")
TerritoryFactor.create!(factor: 0.770, territory: "Jackson", number: 2, exposure: 0.296, state: "OH")
TerritoryFactor.create!(factor: 0.770, territory: "Lawrence", number: 2, exposure: 0.296, state: "OH")
TerritoryFactor.create!(factor: 0.770, territory: "Miami", number: 2, exposure: 0.296, state: "OH")
TerritoryFactor.create!(factor: 0.770, territory: "Montgomery", number: 2, exposure: 0.296, state: "OH")
TerritoryFactor.create!(factor: 0.770, territory: "Pike", number: 2, exposure: 0.296, state: "OH")
TerritoryFactor.create!(factor: 0.770, territory: "Preble", number: 2, exposure: 0.296, state: "OH")
TerritoryFactor.create!(factor: 0.770, territory: "Ross", number: 2, exposure: 0.296, state: "OH")
TerritoryFactor.create!(factor: 0.770, territory: "Scioto", number: 2, exposure: 0.296, state: "OH")
TerritoryFactor.create!(factor: 0.770, territory: "Vinten", number: 2, exposure: 0.296, state: "OH")
TerritoryFactor.create!(factor: 0.770, territory: "Warren", number: 2, exposure: 0.296, state: "OH")
TerritoryFactor.create!(factor: 1.323, territory: "Ashtabula", number: 3, exposure: 0.063, state: "OH")
TerritoryFactor.create!(factor: 1.323, territory: "Geauga", number: 3, exposure: 0.063, state: "OH")
TerritoryFactor.create!(factor: 1.323, territory: "Lake", number: 3, exposure: 0.063, state: "OH")
TerritoryFactor.create!(factor: 1.323, territory: "Mahoning", number: 3, exposure: 0.063, state: "OH")
TerritoryFactor.create!(factor: 1.323, territory: "Portage", number: 3, exposure: 0.063, state: "OH")
TerritoryFactor.create!(factor: 1.323, territory: "Trumbull", number: 3, exposure: 0.063, state: "OH")
TerritoryFactor.create!(factor: 1.138, territory: "Belmont", number: 4, exposure: 0.013, state: "OH")
TerritoryFactor.create!(factor: 1.138, territory: "Columbiana", number: 4, exposure: 0.013, state: "OH")
TerritoryFactor.create!(factor: 1.138, territory: "Jefferson", number: 4, exposure: 0.013, state: "OH")
TerritoryFactor.create!(factor: 1.138, territory: "Monroe ", number: 4, exposure: 0.013, state: "OH")
TerritoryFactor.create!(factor: 1.138, territory: "Washington", number: 4, exposure: 0.013, state: "OH")
TerritoryFactor.create!(factor: 1.415, territory: "Cuyahoga", number: 5, exposure: 0.138, state: "OH")
TerritoryFactor.create!(factor: 1.415, territory: "Lorain", number: 5, exposure: 0.138, state: "OH")
TerritoryFactor.create!(factor: 1.184, territory: "Medina", number: 6, exposure: 0.136, state: "OH")
TerritoryFactor.create!(factor: 1.184, territory: "Stark", number: 6, exposure: 0.136, state: "OH")
TerritoryFactor.create!(factor: 1.184, territory: "Summit", number: 6, exposure: 0.136, state: "OH")
TerritoryFactor.create!(factor: 1.701, territory: "Los Angeles", number:  0, exposure:  0, state: "CA")
TerritoryFactor.create!(factor: 1.701, territory: "Orange", number:  0, exposure:  0, state: "CA")
TerritoryFactor.create!(factor: 1.701, territory: "Riverside", number:  0, exposure:  0, state: "CA")
TerritoryFactor.create!(factor: 1.701, territory: "San Bernadino", number:  0, exposure:  0, state: "CA")
TerritoryFactor.create!(factor: 1.266, territory: "Imperial", number:  0, exposure:  0, state: "CA")
TerritoryFactor.create!(factor: 1.266, territory: "San Diego", number:  0, exposure:  0, state: "CA")
TerritoryFactor.create!(factor: 1.794, territory: "Kern", number:  0, exposure:  0, state: "CA")
TerritoryFactor.create!(factor: 1.794, territory: "Ventura", number:  0, exposure:  0, state: "CA")
TerritoryFactor.create!(factor: 1.000, territory: "Remainder", number:  0, exposure:  0, state: "CA")
TerritoryFactor.create!(factor: 1.000, territory: "SLO", number:  0, exposure:  0, state: "CA")
TerritoryFactor.create!(factor: 1.000, territory: "Santa Barbara", number:  0, exposure:  0, state: "CA")
TerritoryFactor.create!(factor: 1.000, territory: "San Mateo", number:  0, exposure:  0, state: "CA")
TerritoryFactor.create!(factor: 0.995, territory: "Fresno", number:  0, exposure:  0, state: "CA")
TerritoryFactor.create!(factor: 0.995, territory: "Madera", number:  0, exposure:  0, state: "CA")
TerritoryFactor.create!(factor: 0.995, territory: "Mariposa", number:  0, exposure:  0, state: "CA")
TerritoryFactor.create!(factor: 0.995, territory: "Monterey", number:  0, exposure:  0, state: "CA")
TerritoryFactor.create!(factor: 0.995, territory: "San Benito", number:  0, exposure:  0, state: "CA")
TerritoryFactor.create!(factor: 0.995, territory: "Santa Clara", number:  0, exposure:  0, state: "CA")
TerritoryFactor.create!(factor: 0.995, territory: "Santa Cruz", number:  0, exposure:  0, state: "CA")
TerritoryFactor.create!(factor: 0.995, territory: "Stanislaus", number:  0, exposure:  0, state: "CA")

RiskFactor.create!(min_factor: 0.05, max_factor: 0.05, criteria: "CLAIMS FREE 3 TO 5 YEARS")
RiskFactor.create!(min_factor: 0.05, max_factor: 0.05, criteria: "CLAIMS FREE 5 YEARS +")
RiskFactor.create!(min_factor: 0.05, max_factor: 0.05, criteria: "RISK MANAGEMENT ")
RiskFactor.create!(min_factor: 0.05, max_factor: 0.05, criteria: "UNUSUAL RISK CHARACTERISTICS")
RiskFactor.create!(min_factor: 0.05, max_factor: 0.05, criteria: "GROUP DISCOUNT")
RiskFactor.create!(min_factor: 0.05, max_factor: 0.05, criteria: "PART TIME ")
RiskFactor.create!(min_factor: 0.05, max_factor: 0.05, criteria: "NEW PRACTIONER")
RiskFactor.create!(min_factor: 0.05, max_factor: 0.05, criteria: "PREMISES CARE/CONDITION")
RiskFactor.create!(min_factor: 0.05, max_factor: 0.05, criteria: "EMPLOYEE SELECTION, TRAINING, EXP, SUPERVISION")
RiskFactor.create!(min_factor: 0.05, max_factor: 0.05, criteria: "RECORD KEEPING PRACTICES")
RiskFactor.create!(min_factor: 0.05, max_factor: 0.05, criteria: "COOPERATION W/UNDERWRITING & CLAIMS DEPTS")
RiskFactor.create!(min_factor: 0.05, max_factor: 0.05, criteria: "GROUP LOSS EXPERIENCE (NOT OTHERWISE RECOGNIZED)")

SpecialtyFactor.create!(factor: 0.426, spec_name: "Allergy", spec_surgery: "", spec_class: "1", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.426, spec_name: "Psychiatry", spec_surgery: "No", spec_class: "1", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.426, spec_name: "Retired Physicians", spec_surgery: "No", spec_class: "1", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.531, spec_name: "Administrative Medicine", spec_surgery: "No", spec_class: "2", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.531, spec_name: "Nuclear Medicine", spec_surgery: "No", spec_class: "2", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.635, spec_name: "Office Orthopedics - No Surgery", spec_surgery: "No", spec_class: "3", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.635, spec_name: "Colon & Rectal Surgery", spec_surgery: "", spec_class: "3", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.635, spec_name: "Forensic Medicine", spec_surgery: "No", spec_class: "3", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.635, spec_name: "General Surgery - Office Practice", spec_surgery: "No", spec_class: "3", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.635, spec_name: "Gynecology - Office/Consultative", spec_surgery: "No Major", spec_class: "3", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.635, spec_name: "Neurosurgery - Office Practice Only", spec_surgery: "No", spec_class: "3", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.635, spec_name: "Ophthalmology - No Surgery", spec_surgery: "No", spec_class: "3", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.635, spec_name: "Osteopathic Manipulative Medicine", spec_surgery: "", spec_class: "3", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.635, spec_name: "Otorhinolaryngology - No Surgery", spec_surgery: "No", spec_class: "3", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.635, spec_name: "Thoracic Surgery - Office Only", spec_surgery: "No", spec_class: "3", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.635, spec_name: "Toxicology", spec_surgery: "No", spec_class: "3", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.635, spec_name: "Urology - Office Practice", spec_surgery: "No", spec_class: "3", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.739, spec_name: "Dermatology", spec_surgery: "No", spec_class: "4", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.739, spec_name: "Neonatalogy", spec_surgery: "No", spec_class: "4", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.739, spec_name: "Occupational Medicine", spec_surgery: "No", spec_class: "4", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.739, spec_name: "Ophthalmology - Surgery", spec_surgery: "No", spec_class: "4", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.739, spec_name: "Pediatrics", spec_surgery: "", spec_class: "4", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.844, spec_name: "Hyperbaric Medicine", spec_surgery: "No", spec_class: "5", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.844, spec_name: "IM - Nephrology", spec_surgery: "Minor", spec_class: "5", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.844, spec_name: "IM - Rheumatology", spec_surgery: "Minor", spec_class: "5", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.844, spec_name: "IM- Endocrinology", spec_surgery: "Minor", spec_class: "5", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.844, spec_name: "Neurology-Assisting", spec_surgery: "Minor", spec_class: "5", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.844, spec_name: "Neurosurgery - Assisting", spec_surgery: "", spec_class: "5", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.844, spec_name: "Office Orthopedics - Assisting", spec_surgery: "Minor", spec_class: "5", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.844, spec_name: "Oral Surgeon", spec_surgery: "Minor", spec_class: "5", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.844, spec_name: "Otorhinolaryngology (ENT) Minor", spec_surgery: "Minor", spec_class: "5", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.844, spec_name: "Podiatry", spec_surgery: "Minor", spec_class: "5", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.844, spec_name: "Preventive Medicine", spec_surgery: "Minor", spec_class: "5", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.844, spec_name: "Surgical Assisting", spec_surgery: "Minor", spec_class: "5", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.844, spec_name: "Thoracic Surgery - Assisting", spec_surgery: "Minor", spec_class: "5", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.844, spec_name: "Colon & Rectal Surgery", spec_surgery: "Minor", spec_class: "5", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.844, spec_name: "General Surgery - Local Anesthetic", spec_surgery: "No Major", spec_class: "5", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.844, spec_name: "Gynecology  - Office/Assisting", spec_surgery: "Minor", spec_class: "5", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.844, spec_name: "Urology - Assisting", spec_surgery: "No Major", spec_class: "5", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.896, spec_name: "Physical Medicine and Rehabilitation", spec_surgery: "", spec_class: "6", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.948, spec_name: "Cardiology - No Cardiac Catheterization", spec_surgery: "", spec_class: "7", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 0.948, spec_name: "Geriatrics", spec_surgery: "", spec_class: "7", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.000, spec_name: "Family//General Practice - Office/Ambulatory", spec_surgery: "", spec_class: "8", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.000, spec_name: "Hospitalist", spec_surgery: "", spec_class: "8", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.000, spec_name: "IM – NOC", spec_surgery: "", spec_class: "8", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.052, spec_name: "IM- Gastroenterology", spec_surgery: "", spec_class: "9", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.052, spec_name: "Radiation Oncology", spec_surgery: "No", spec_class: "9", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.157, spec_name: "IM - Hematology", spec_surgery: "No", spec_class: "10", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.157, spec_name: "IM – Infectious Diseases", spec_surgery: "", spec_class: "10", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.157, spec_name: "IM - Pulmonary Disease", spec_surgery: "", spec_class: "10", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.157, spec_name: "Ophthalmology - Corneal & Lens", spec_surgery: "", spec_class: "10", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.157, spec_name: "Pathology", spec_surgery: "", spec_class: "10", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.157, spec_name: "Neurology-Including Child", spec_surgery: "", spec_class: "10", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.261, spec_name: "Physical Medicine - Interventional", spec_surgery: "", spec_class: "11", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.365, spec_name: "Family//General Practice - Major Surgery (C- Section)", spec_surgery: "No Major", spec_class: "12", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.365, spec_name: "Family//General Practice - Minor Surgery", spec_surgery: "Incl Major", spec_class: "12", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.365, spec_name: "Family//General Practice - Obstetrics", spec_surgery: "", spec_class: "12", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.365, spec_name: "Dermatology2", spec_surgery: "", spec_class: "12", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.470, spec_name: "Anesthesiology", spec_surgery: "", spec_class: "13", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.470, spec_name: "Colon & Rectal Surgery", spec_surgery: "", spec_class: "13", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.574, spec_name: "Urological Surgery", spec_surgery: "", spec_class: "14", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.678, spec_name: "Cardiology - Cardiac Catheterization", spec_surgery: "", spec_class: "15", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.678, spec_name: "Emergency Medicine", spec_surgery: "", spec_class: "15", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.678, spec_name: "Hand Surgery", spec_surgery: "", spec_class: "15", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.678, spec_name: "Radiology-Diagnostic and Invasive", spec_surgery: "", spec_class: "15", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.991, spec_name: "Otorhinolaryngology (ENT) Major", spec_surgery: "", spec_class: "16", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 2.095, spec_name: "Radiology-Interventional", spec_surgery: "", spec_class: "17", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 2.721, spec_name: "Plastic Surgery", spec_surgery: "", spec_class: "18", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 3.243, spec_name: "Family//General Practice - Major Surgery (Abdominal)", spec_surgery: "", spec_class: "19", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 3.243, spec_name: "Gynecology", spec_surgery: "", spec_class: "19", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 3.243, spec_name: "Gynecology  - IVF", spec_surgery: "", spec_class: "19", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 3.243, spec_name: "Orthopedic Surgery", spec_surgery: "", spec_class: "19", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 3.347, spec_name: "General Surgery - NOC", spec_surgery: "", spec_class: "20", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 3.868, spec_name: "Orthopedic Surgery -Spine", spec_surgery: "", spec_class: "21", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 3.973, spec_name: "Vascular Surgery", spec_surgery: "", spec_class: "22", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 4.077, spec_name: "OB/GYN", spec_surgery: "", spec_class: "23", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 4.599, spec_name: "Thoracic Surgery", spec_surgery: "", spec_class: "24", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 6.633, spec_name: "Neurosurgery", spec_surgery: "", spec_class: "25", spec_code: "", state: "CO")
SpecialtyFactor.create!(factor: 1.000, spec_name: "Aerospace Medicine", spec_surgery: "", spec_class: "1", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.000, spec_name: "Dermatology", spec_surgery: "No", spec_class: "1", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.000, spec_name: "Dermatology", spec_surgery: "Minor", spec_class: "1", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.000, spec_name: "Diabetes", spec_surgery: "No", spec_class: "1", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.000, spec_name: "Endocrinology", spec_surgery: "No", spec_class: "1", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.000, spec_name: "Family Practice", spec_surgery: "No", spec_class: "1", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.000, spec_name: "General Practice", spec_surgery: "No", spec_class: "1", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.000, spec_name: "General Preventive Medicine", spec_surgery: "", spec_class: "1", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.000, spec_name: "Infectious Diseases", spec_surgery: "No", spec_class: "1", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.000, spec_name: "Infectious Diseases", spec_surgery: "Minor", spec_class: "1", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.000, spec_name: "Internal Medicine", spec_surgery: "No", spec_class: "1", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.000, spec_name: "Legal Medicine", spec_surgery: "", spec_class: "1", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.000, spec_name: "Nuclear Medicine", spec_surgery: "", spec_class: "1", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.000, spec_name: "Opthalmology", spec_surgery: "No", spec_class: "1", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.000, spec_name: "Otorhinolaryngology", spec_surgery: "No", spec_class: "1", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.000, spec_name: "Pathology", spec_surgery: "No", spec_class: "1", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.000, spec_name: "Pharmacology - Clinical", spec_surgery: "", spec_class: "1", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.000, spec_name: "Physician", spec_surgery: "No", spec_class: "1", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.000, spec_name: "Physician - Retired Volunteer", spec_surgery: "", spec_class: "1", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.000, spec_name: "Psychosomatic  Medicine", spec_surgery: "", spec_class: "1", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.000, spec_name: "Pulmonary Diseases", spec_surgery: "No", spec_class: "1", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 0.929, spec_name: "Allergy", spec_surgery: "", spec_class: "1A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 0.929, spec_name: "Forensic Medicine", spec_surgery: "", spec_class: "1A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 0.929, spec_name: "Nutrition", spec_surgery: "", spec_class: "1A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 0.929, spec_name: "Occupational  Medicine", spec_surgery: "", spec_class: "1A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 0.929, spec_name: "Psychiatry (ECT)", spec_surgery: "", spec_class: "1A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 0.929, spec_name: "Psychiatry (No ECT)", spec_surgery: "", spec_class: "1A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 0.929, spec_name: "Public Health", spec_surgery: "", spec_class: "1A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 0.929, spec_name: "Rheumatology", spec_surgery: "No", spec_class: "1A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.509, spec_name: "Diabetes", spec_surgery: "Minor", spec_class: "2", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.509, spec_name: "Endocrinology", spec_surgery: "Minor", spec_class: "2", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.509, spec_name: "Family Practice", spec_surgery: "Minor", spec_class: "2", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.509, spec_name: "General Practice", spec_surgery: "Minor", spec_class: "2", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.509, spec_name: "Intensive Care Medicine", spec_surgery: "", spec_class: "2", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.509, spec_name: "Opthalmology", spec_surgery: "Minor", spec_class: "2", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.509, spec_name: "Pathology", spec_surgery: "Minor", spec_class: "2", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.509, spec_name: "Pediatrics", spec_surgery: "Minor", spec_class: "2", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.509, spec_name: "Physician", spec_surgery: "Minor", spec_class: "2", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.509, spec_name: "Surgery - Opthalmology", spec_surgery: "", spec_class: "2", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.509, spec_name: "Surgery - Opthalmology (Lens Implants)", spec_surgery: "", spec_class: "2", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.557, spec_name: "Gastroenterology", spec_surgery: "Minor", spec_class: "2A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.557, spec_name: "Radiology", spec_surgery: "No Major", spec_class: "2A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.060, spec_name: "Cardiovascular  Disease", spec_surgery: "No", spec_class: "2B", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.060, spec_name: "Dermatology", spec_surgery: "No Major", spec_class: "2B", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.060, spec_name: "Gastroenterology", spec_surgery: "No", spec_class: "2B", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.060, spec_name: "Geriatrics", spec_surgery: "No", spec_class: "2B", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.060, spec_name: "Geriatrics", spec_surgery: "Minor", spec_class: "2B", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.060, spec_name: "Gynecology", spec_surgery: "No", spec_class: "2B", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.060, spec_name: "Hematology", spec_surgery: "No", spec_class: "2B", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.060, spec_name: "Nephrology", spec_surgery: "No", spec_class: "2B", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.060, spec_name: "Neurology", spec_surgery: "No", spec_class: "2B", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.060, spec_name: "Radiology-diagnostic", spec_surgery: "No", spec_class: "2B", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.060, spec_name: "Urgent Care", spec_surgery: "", spec_class: "2B", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.099, spec_name: "Nephrology", spec_surgery: "Minor", spec_class: "2C", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.099, spec_name: "Pediatrics", spec_surgery: "No", spec_class: "2C", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.099, spec_name: "Physiatry", spec_surgery: "", spec_class: "2C", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.099, spec_name: "Physical Medicine & Rehabilitation", spec_surgery: "", spec_class: "2C", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.622, spec_name: "Broncho  Esophagology", spec_surgery: "", spec_class: "3", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.622, spec_name: "Cardiovascular  Disease", spec_surgery: "No Major", spec_class: "3", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.622, spec_name: "Neonatology", spec_surgery: "", spec_class: "3", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.622, spec_name: "Physician", spec_surgery: "No Major", spec_class: "3", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.622, spec_name: "Surgery - Colon & Rectal", spec_surgery: "", spec_class: "3", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.622, spec_name: "Surgery - Endocrinology", spec_surgery: "", spec_class: "3", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.622, spec_name: "Surgery - Gastroenterology", spec_surgery: "", spec_class: "3", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.622, spec_name: "Surgery - Geriatrics", spec_surgery: "", spec_class: "3", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.622, spec_name: "Surgery - Neoplastic", spec_surgery: "", spec_class: "3", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.622, spec_name: "Surgery - Nephrology", spec_surgery: "", spec_class: "3", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.622, spec_name: "Surgery - Opthalmology - Radial Kerototomy", spec_surgery: "", spec_class: "3", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.622, spec_name: "Surgery - Urology", spec_surgery: "", spec_class: "3", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.622, spec_name: "Surgery- General Pracitce or Family Practice", spec_surgery: "", spec_class: "3", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.365, spec_name: "Cardiovascular  Disease", spec_surgery: "Minor", spec_class: "3A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.365, spec_name: "Gynecology", spec_surgery: "Minor", spec_class: "3A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.365, spec_name: "Hematology", spec_surgery: "Minor", spec_class: "3A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.365, spec_name: "Laryngology", spec_surgery: "No", spec_class: "3A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.365, spec_name: "Laryngology", spec_surgery: "Minor", spec_class: "3A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.365, spec_name: "Neurology", spec_surgery: "Minor", spec_class: "3A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.365, spec_name: "Otology", spec_surgery: "No", spec_class: "3A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.365, spec_name: "Otology", spec_surgery: "Minor", spec_class: "3A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.365, spec_name: "Otorhinolaryngology", spec_surgery: "Minor", spec_class: "3A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.365, spec_name: "Radiology-diagnostic", spec_surgery: "Minor", spec_class: "3A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.365, spec_name: "Rhinology", spec_surgery: "No", spec_class: "3A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.365, spec_name: "Rhinology", spec_surgery: "Minor", spec_class: "3A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.649, spec_name: "Anesthesiology", spec_surgery: "", spec_class: "3B", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.649, spec_name: "Family Practice - Prenatal Only", spec_surgery: "Minor", spec_class: "3B", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.649, spec_name: "General Practice - Prenatal Only", spec_surgery: "Minor", spec_class: "3B", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.649, spec_name: "Internal Medicine", spec_surgery: "No Major", spec_class: "3B", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.649, spec_name: "Internal Medicine", spec_surgery: "Minor", spec_class: "3B", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.760, spec_name: "General Practice (Less than 50 Deliveries)", spec_surgery: "", spec_class: "4", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.760, spec_name: "Surgery - ENT No Plastic", spec_surgery: "", spec_class: "4", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.760, spec_name: "Surgery - ENT Non-Elective Plastic", spec_surgery: "", spec_class: "4", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.760, spec_name: "Surgery - Head & Neck", spec_surgery: "", spec_class: "4", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.760, spec_name: "Surgery - Laryngology", spec_surgery: "", spec_class: "4", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.760, spec_name: "Surgery - Otology", spec_surgery: "", spec_class: "4", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.760, spec_name: "Surgery - Rhinology", spec_surgery: "", spec_class: "4", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 3.076, spec_name: "Family Practice (50-99 Deliveries)", spec_surgery: "", spec_class: "5", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 3.076, spec_name: "General Practice (50-99 Deliveries)", spec_surgery: "", spec_class: "5", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 3.076, spec_name: "Surgery - Abdominal", spec_surgery: "", spec_class: "5", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 3.076, spec_name: "Surgery - Emergency Medicine", spec_surgery: "", spec_class: "5", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 3.076, spec_name: "Surgery - ENT - Elective Plastic", spec_surgery: "", spec_class: "5", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 3.076, spec_name: "Surgery - Gynecology", spec_surgery: "", spec_class: "5", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 3.076, spec_name: "Surgery - Hand", spec_surgery: "", spec_class: "5", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 1.761, spec_name: "Family Practice (Less than 50 Deliveries)", spec_surgery: "", spec_class: "5A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 2.663, spec_name: "Emergency Medicine", spec_surgery: "No Major", spec_class: "5B", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 4.701, spec_name: "Surgery - Cardiac", spec_surgery: "", spec_class: "6", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 4.701, spec_name: "Surgery - Cardiovascular", spec_surgery: "", spec_class: "6", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 4.701, spec_name: "Surgery - Thoracic", spec_surgery: "", spec_class: "6", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 4.701, spec_name: "Surgery - Traumatic", spec_surgery: "", spec_class: "6", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 4.701, spec_name: "Surgery - Vascular", spec_surgery: "", spec_class: "6", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 3.165, spec_name: "Surgery - Orthopedic (No Spine Surgery)", spec_surgery: "", spec_class: "6A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 3.165, spec_name: "Surgery - Plastic", spec_surgery: "", spec_class: "6A", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 3.675, spec_name: "Surgery - Orthopedic (Spine Surgery)", spec_surgery: "", spec_class: "6B", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 4.808, spec_name: "Surgery - General", spec_surgery: "", spec_class: "6C", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 4.960, spec_name: "Surgery - General (including Bariatric Surgery)", spec_surgery: "", spec_class: "6D", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 7.472, spec_name: "Family Practice (100 or more Deliveries)", spec_surgery: "", spec_class: "7", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 7.472, spec_name: "General Practice (100 or more Deliveries)", spec_surgery: "", spec_class: "7", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 7.472, spec_name: "Surgery - OB", spec_surgery: "", spec_class: "7", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 7.472, spec_name: "Surgery - OB/GYN", spec_surgery: "", spec_class: "7", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 6.958, spec_name: "Surgery - Neurology", spec_surgery: "", spec_class: "8", spec_code: "", state: "NC")
SpecialtyFactor.create!(factor: 0.539, spec_name: "Emergency Medicine - no major surgery", spec_surgery: "No", spec_class: "1", spec_code: "80102A", state: "OH")
SpecialtyFactor.create!(factor: 0.539, spec_name: "Administrative Medicine", spec_surgery: "No", spec_class: "1", spec_code: "80178", state: "OH")

BaseRate.create!(rate: 19027, state: "AZ")
BaseRate.create!(rate: 06184, state: "ID")
BaseRate.create!(rate: 14339, state: "NC")
BaseRate.create!(rate: 18709, state: "CO")
BaseRate.create!(rate: 11563, state: "MD")
BaseRate.create!(rate: 17999, state: "OH")
BaseRate.create!(rate: 17497, state: "GA")
BaseRate.create!(rate: 07476, state: "NY")
BaseRate.create!(rate: 13113, state: "WA")

NasRate.create!(rate: 0435, limit_nas: 025000)
NasRate.create!(rate: 0985, limit_nas: 050000)
NasRate.create!(rate: 1235, limit_nas: 100000)

AlliedRate.create!(rate: 500, group: "allied1", constituents: [ "PA" ] )
AlliedRate.create!(rate: 1000, group: "allied2", constituents: [ "NP" ] )
AlliedRate.create!(rate: 1500, group: "allied3", constituents: [ "CNM" ] )
