# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Seed Initial Rates + Factors
SpecialtyFactor.create!(spec_name:"Administrative Medicine", factor:0.57, state:"CA")
SpecialtyFactor.create!(spec_name:"Allergy", factor:0.534, state:"CA")
SpecialtyFactor.create!(spec_name:"Anesthesiology", factor:1.263, state:"CA")
SpecialtyFactor.create!(spec_name:"Cardiac Surgery", factor:1.533, state:"CA")
SpecialtyFactor.create!(spec_name:"Cardiology (with or without arteriography or cardiac cathetarization", factor:1.533, state:"CA")
SpecialtyFactor.create!(spec_name:"Colon & Rectal Surgery", factor:2.38, state:"CA")
SpecialtyFactor.create!(spec_name:"Dermatology (excl dermabrasion & radiation)", factor:0.762, state:"CA")
SpecialtyFactor.create!(spec_name:"Dermatology (incl cosmetic surgery &/or dermabrasion/radiation)", factor:2.211, state:"CA")
SpecialtyFactor.create!(spec_name:"Diagnostic Radiology (with or without arteriography)", factor:1.435, state:"CA")
SpecialtyFactor.create!(spec_name:"Emergency Room practice", factor:2.322, state:"CA")
SpecialtyFactor.create!(spec_name:"Family Practice - Incl obstetrics (resident or teaching)", factor:2.723, state:"CA")
SpecialtyFactor.create!(spec_name:"Family Practice - major surgery", factor:1.96, state:"CA")
SpecialtyFactor.create!(spec_name:"Family Practice - minor surgery", factor:0.849, state:"CA")
SpecialtyFactor.create!(spec_name:"Family Practice - no surgery (teaching ok)", factor:0.639, state:"CA")
SpecialtyFactor.create!(spec_name:"Family Practice - incl obstetrics", factor:2.723, state:"CA")
SpecialtyFactor.create!(spec_name:"Gastroenterology", factor:1.279, state:"CA")
SpecialtyFactor.create!(spec_name:"General Medicine (incl office practice & consulting)", factor:0.639, state:"CA")
SpecialtyFactor.create!(spec_name:"General Practice - Major Surgery", factor:3.567, state:"CA")
SpecialtyFactor.create!(spec_name:"General Practice - Minor Surgery", factor:0.849, state:"CA")
SpecialtyFactor.create!(spec_name:"General Practice - No Surgery", factor:0.639, state:"CA")
SpecialtyFactor.create!(spec_name:"General Practice - Incl Obstetrics", factor:3.567, state:"CA")
SpecialtyFactor.create!(spec_name:"General Practice/Family Practice - General Anesthesia", factor:3.567, state:"CA")
SpecialtyFactor.create!(spec_name:"General Preventative Medicine", factor:0.639, state:"CA")
SpecialtyFactor.create!(spec_name:"General Surgery", factor:3.567, state:"CA")
SpecialtyFactor.create!(spec_name:"Gynecology", factor:2.185, state:"CA")
SpecialtyFactor.create!(spec_name:"Gynecology (incl cosmetics)", factor:2.185, state:"CA")
SpecialtyFactor.create!(spec_name:"Internal Medicine (with or without coronary arteriography, radiation)", factor:1.435, state:"CA")
SpecialtyFactor.create!(spec_name:"Internal Medicine (no arteriology or radiation)", factor:1, state:"CA")
SpecialtyFactor.create!(spec_name:"Neonatology", factor:1.361, state:"CA")
SpecialtyFactor.create!(spec_name:"Neurology (with or without shock treatment)", factor:1.437, state:"CA")
SpecialtyFactor.create!(spec_name:"Neurosurgery", factor:5.835, state:"CA")
SpecialtyFactor.create!(spec_name:"Nuclear Medicine", factor:0.579, state:"CA")
SpecialtyFactor.create!(spec_name:"Obstetrics & Gynecology", factor:4.696, state:"CA")
SpecialtyFactor.create!(spec_name:"Occupational Medicine", factor:0.488, state:"CA")
SpecialtyFactor.create!(spec_name:"Ophthalmology (no surgery)", factor:0.548, state:"CA")
SpecialtyFactor.create!(spec_name:"Ophthalmology (minor surgery)", factor:0.774, state:"CA")
SpecialtyFactor.create!(spec_name:"Ophthalmology (major surgery)", factor:1.285, state:"CA")
SpecialtyFactor.create!(spec_name:"Oral & Maxillofacial surgery", factor:1.2, state:"CA")
SpecialtyFactor.create!(spec_name:"Orthopedic Surgery ", factor:3.143, state:"CA")
SpecialtyFactor.create!(spec_name:"Otolaryngology (incl plastic surgery)", factor:2.442, state:"CA")
SpecialtyFactor.create!(spec_name:"Otolaryngology (NO plastic surgery)", factor:1.754, state:"CA")
SpecialtyFactor.create!(spec_name:"Pathology", factor:0.932, state:"CA")
SpecialtyFactor.create!(spec_name:"Pediatrics", factor:1.036, state:"CA")
SpecialtyFactor.create!(spec_name:"Physical Medicine & Rehabilitation", factor:0.544, state:"CA")
SpecialtyFactor.create!(spec_name:"Physical Medicine & Rehab (minor procedures)", factor:0.87, state:"CA")
SpecialtyFactor.create!(spec_name:"Physical Medicine & Rehab (major procedures)", factor:1.144, state:"CA")
SpecialtyFactor.create!(spec_name:"Plastic Surgery", factor:2.865, state:"CA")
SpecialtyFactor.create!(spec_name:"Psychiatry ", factor:0.675, state:"CA")
SpecialtyFactor.create!(spec_name:"Pulmonary Disease", factor:1.442, state:"CA")
SpecialtyFactor.create!(spec_name:"Surgery Specialist - office practice & assisting", factor:1.461, state:"CA")
SpecialtyFactor.create!(spec_name:"Surgical Assistant", factor:1.461, state:"CA")
SpecialtyFactor.create!(spec_name:"Therapeutic Radiology", factor:1.419, state:"CA")
SpecialtyFactor.create!(spec_name:"Thoracic Surgery", factor:3.354, state:"CA")
SpecialtyFactor.create!(spec_name:"Urology", factor:1.8, state:"CA")

ClaimFactor.create!(policy_year:1, factor:0.35, state:"CA")
ClaimFactor.create!(policy_year:2, factor:0.6, state:"CA")
ClaimFactor.create!(policy_year:3, factor:0.8, state:"CA")
ClaimFactor.create!(policy_year:4, factor:0.92, state:"CA")
ClaimFactor.create!(policy_year:5, factor:1, state:"CA")

DedFactor.create!(deductible:0, factor:1, state:"CA")
DedFactor.create!(deductible:5000, factor:0.95, state:"CA")
DedFactor.create!(deductible:10000, factor:0.9, state:"CA")
DedFactor.create!(deductible:25000, factor:0.8, state:"CA")

TerritoryFactor.create!(county:"Los Angeles", factor:1.701, state:"CA")
TerritoryFactor.create!(county:"Orange", factor:1.701, state:"CA")
TerritoryFactor.create!(county:"Riverside", factor:1.701, state:"CA")
TerritoryFactor.create!(county:"San Bernadino", factor:1.701, state:"CA")
TerritoryFactor.create!(county:"Imperial", factor:1.266, state:"CA")
TerritoryFactor.create!(county:"San Diego", factor:1.266, state:"CA")
TerritoryFactor.create!(county:"Kern", factor:1.794, state:"CA")
TerritoryFactor.create!(county:"Ventura", factor:1.794, state:"CA")
TerritoryFactor.create!(county:"Remainder", factor:1, state:"CA")
TerritoryFactor.create!(county:"SLO", factor:1, state:"CA")
TerritoryFactor.create!(county:"Santa Barbara", factor:1, state:"CA")
TerritoryFactor.create!(county:"San Mateo", factor:1, state:"CA")
TerritoryFactor.create!(county:"Fresno", factor:0.995, state:"CA")
TerritoryFactor.create!(county:"Madera", factor:0.995, state:"CA")
TerritoryFactor.create!(county:"Mariposa", factor:0.995, state:"CA")
TerritoryFactor.create!(county:"Monterey", factor:0.995, state:"CA")
TerritoryFactor.create!(county:"San Benito", factor:0.995, state:"CA")
TerritoryFactor.create!(county:"Santa Clara", factor:0.995, state:"CA")
TerritoryFactor.create!(county:"Santa Cruz", factor:0.995, state:"CA")
TerritoryFactor.create!(county:"Stanislaus", factor:0.995, state:"CA")

EntityFactory.create!(entity:"Individual", factor:1, state:"CA")
EntityFactory.create!(entity:"Entity", factor:1.08, state:"CA")

LimitFactor.create!(limit:"1,000,000/3,000,000", factor:1, state:"CA")
LimitFactor.create!(limit:"2,000,000/4,000,000", factor:1.25, state:"CA")

NasRate.create!(limit:25000, rate:435, state:"CA")
NasRate.create!(limit:50000, rate:985, state:"CA")
NasRate.create!(limit:100000, rate:1235, state:"CA")

AlliedRate.create!(category:"Allied1", rate:500, state:"CA", elements:[ "PA" ])
AlliedRate.create!(category:"Allied2", rate:1000, state:"CA", elements:[ "NP" ])
AlliedRate.create!(category:"Allied3", rate:1500, state:"CA", elements:[ "CNM" ])
StateRate.create!(rate:7757, state:"CA")
